### ISSUE TITLE
Azure Sphere OS update 20.10

### ISSUE THREAD

**Issue by KMOGAKI** [Cactusphere/Cactusphere-100#46]
2020年10月14日にAzure Sphere OS 20.10 がRetail Eval リリースされました。また、評価期間中に使用するための評価版のSDKもリリースされました。リリース後3週間は後方互換性を確認する評価期間になります。
詳しいリリーススキームについてはソフトウェアマニュアル (3.4.2. Azure Sphere OS / Azure Sphere SDK のリリース)を参照してください。
また、リリース内容については下記を参照してください。
https://techcommunity.microsoft.com/t5/internet-of-things/azure-sphere-20-10-is-now-available-for-compatibility-testing/ba-p/1780255

The Azure Sphere OS update 20.10 had released from Microsoft via the Retail Eval feed on October 14, 2020. And an evaluation SDK for use during the evaluation period has also been released. For more information, please refer to the post of Microsoft Tech Community.
https://techcommunity.microsoft.com/t5/internet-of-things/azure-sphere-20-10-is-now-available-for-compatibility-testing/ba-p/1780255

**Comment by atKeitaroTakahashi** [comment]
Azure Sphere SDK 20.10 に対応した Cactusphere-100 接点入力モデル v201110 及び Cactusphere-100 RS485モデル v201110 をリリースしました。
https://github.com/Cactusphere/Cactusphere-100/releases/tag/DI_v201110
https://github.com/Cactusphere/Cactusphere-100/releases/tag/RS485_v201110
