### ISSUE TITLE
Azure Sphere OS update 20.07

### ISSUE THREAD

**Issue by kodagiri** [Cactusphere/Cactusphere-100#7]
Azure Sphere OS 20.07 がリリースされました。今後14日間は後方互換性を確認する評価期間になります。今から我々は後方互換性の検証を開始します。進展があればこの issue で共有します。我々の確認の後でそれぞれの環境で検証をお願いします。その際に何か問題があればお知らせください。詳しいリリーススキームについてはソフトウエアマニュアル (3.4.2. Azure Sphere OS / Azure Sphere SDK のリリース)を参照してください。

The Azure Sphere OS update 20.07 had released from Microsoft via the Retail Eval feed. We will verify Cactusphere-100 applications from right away and share the progress on this issue. After the verification, please verify that devices operate properly with the release on your environment. Regarding to back compatibility of Cactusphere-100, if you encounter any problem with the release, please let us know on the issue.

For more information, please refer to the post of Microsoft Tech Community.
https://azure.microsoft.com/ja-jp/updates/azure-sphere-os-update-2007-is-available-for-compatibility-testing/

**Comment by kodagiri** [comment]
Azure Sphere OS 20.07 と Cactusphere-100 の組み合わせで、適切に機能することを検証しました。retail feed がリリースされる評価期間が終わるまでの間、環境の差分などを検証することができます。何か問題があればこのチケット上でお知らせください。

We have confirmed that the Cactupshere-100 applications work properly with the 20.07. Since there may be some difference depending on environment, please verify whether your Cactusphere-100 work properly until the retail feed (the end of the evaluation period). Regarding to backward compatibility of Cactusphere-100, if you encounter any problem with the 20.07, please let us know on the issue.

We have confirmed the application below:
- DI_v1.0.0

**Comment by naomitodori** [comment]
Azure Sphere OS 20.07 において、下記の問題が確認されています。

- `azsphere dev recover` コマンドを使用して Azure Sphere OS 20.07 にアップデートした場合、
EthernetのMACアドレスがランダムではなく同一となる

これにより、OS 20.07 に recover し、Ethernetでネットワーク接続を行うデバイスが複数台同一ネットワークに存在すると
全てのデバイスでEthernet MACアドレスが同じであるため、DHCPでIPアドレスが取得できずに通信ができなくなる等の問題が発生します。

この問題については、現在 RetailEval Feedでリリースされている Azure Sphere OS 20.08 で修正されています。 #16 
https://techcommunity.microsoft.com/t5/internet-of-things/azure-sphere-os-update-20-08-now-available-for-compatibility/ba-p/1579638
- Fixed issue in 20.07 where device recovery would not result in a random MAC address for Ethernet on an Ethernet configured device.

なお、 Azure Sphere OS 20.06 から 20.07に OTAでOSアップデートを実施した場合、
OS 20.06 の MACアドレスが引き継がれるため、この問題は発生しません。

**Comment by naomitodori** [comment]
> Azure Sphere OS 20.07 において、下記の問題が確認されています。
> 
> * `azsphere dev recover` コマンドを使用して Azure Sphere OS 20.07 にアップデートした場合、
>   EthernetのMACアドレスがランダムではなく同一となる
> 

下記に、リカバリー方法等の情報が記載されています。
https://techcommunity.microsoft.com/t5/internet-of-things/known-issue-azure-sphere-recovery-procedure-in-manufacturing/ba-p/1594381

OS 20.07にrecoverした場合は、OS 20.06 にrecoverするか OS 20.08のリリースを待つよう記載がありますが、
OS 20.08Update1がRetailフィードでリリースされたため、 `azsphere dev recover` でOSのアップデートを行ってください。
